QUOTES = ['If all you can do is crawl, start crawling. - Rumi',
          'Opportunity does not knock, it presents itself when you beat down the door. - Kyle Chandler',
          'If we did the things we are capable of, we would astound ourselves. - Thomas Edison ',
          'There is no man living that can not do more than he thinks he can. - Henry Ford',
          'Never give up on something that you can’t go a day without thinking about. - Winston Churchill',
          'Most people are other people. Their thoughts are someo ne elses opinions, their lives a mimicry, their passions a quotation. - Oscar Wilde',
          'Man cannot remake himself without suffering for he is both the marble and the sculptor. - Alexis Carrel',
          'A creative man is motivated by the desire  to achieve, not by the desire to beat others. - Ayn Rand',
          'It is never too late to be what you might have been. - George Eliot',
          'Being defeated is often a temporary condition. Giving up is what makes it permanent. - Marilyn Vos S avant',
          'All our dreams can come true–if we have the courage to pursue them. - Walt Disney',
          'If you’re going through hell, keep going. - Winston Churchill',
          'The greatest pleasure in life is doing what people say you cannot do. - Walter Bag ehot',
          'Enjoy the little things, for one day you may look back and realize they were the big things. - Robert Brault',
          'You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus',
          'How wonde rful it is that nobody need wait a single moment before beginning to improve the world. - Anne Frank',
          'Change your thoughts and you change your world. - Norman Vincent Peale',
          'Your time is limited, so don’t waste it living someone else’s  life. - Steve Jobs',
          'We enjoy warmth because we have been cold. We appreciate light because we have been in darkness. By the same token, we can experience joy because we have known sorrow. - David L. Weatherford',
          'The woods are lovely,  dark and deep. But I have promises to keep, And miles to go before I sleep, And miles to go before I sleep. - Robert Frost',
          'The most common way people give up their power is by thinking they don’t have any. - Alice Walker',
          'Withou t ambition, one starts nothing. Without work, one finishes nothing. The prize will not be sent to you. You have to win it. - Ralph Waldo Emerson',
          'The best revenge is massive success. - Frank Sinatra',
          'Whatever the mind can conceiv e and believe, it can achieve. - Napoleon Hill',
          'Dreams come true. Without that possibility, nature would not incite us to have them. - John Updike',
          'If you don’t like how things are, change it! You’re not a tree. - Jim Rohn',
          'Every body is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid. - Albert Einstein',
          'The future belongs to those who believe in the beauty of their dreams. - Eleanor Roos evelt',
          'We all have bad days, but one thing is true; no cloud is so dark that the sun can’t shine through. - Miranda Kerr',
          'Don’t fear failure, in great attempts it is glorious even to fail. - Bruce Lee',
          'There are no shortcuts t o any place worth going. - Beverly Sills',
          'You will face many defeats in your life, but never let yourself be defeated. - Maya Angelou',
          'The secret to getting ahead is getting started. - Mark Twain',
          'If you don’t run your own lif e, somebody else will. - John Atkinson',
          'Learn the rules so you know how to break them properly. - Dalai Lama',
          'A mediocre person tells. A good person explains. A superior person demonstrates. A great person inspires others to see for th emselves. - Harvey MacKay',
          'Act as if what you do makes a difference. It does. - William James',
          'Happiness is the meaning and the purpose of life, the whole aim and end of human existence- Aristotle',
          'I urge you to please notice when you  are happy, and exclaim or murmur or think at some point, “If this isn’t nice, I don’t know what is."- Kurt Vonnegut',
          'Even if you are on the right track, you’ll get run over if you just sit there. - Will Rogers',
          'Be proud of every sc ar on your heart, each one holds a lifetimes worth of lessons. - Wallace Stegner',
          'Never stand begging for that which you have the power to earn. - Miguel de Cervantes',
          'You have enemies? Good. That means you’ve stood up for somethi ng, sometime in your life. - Winston Churchill',
          'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein',
          'What you do today can improve all yo ur tomorrows. - Ralph Marston',
          'Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi',
          'The highest reward for a person’s toil is not what they get for it, but what they become by it. - John Ruskin',
          ' The difference between an optimist and a pessimist? An optimist laughs to forget but a pessimist forgets to laugh. - Tom Bodett',
          'Keep your face always toward the sunshine and shadows will fall behind you. - Walt Whitman',
          'A great a ttitude becomes a great day which becomes a great month which becomes a great year which becomes a great life. - Mandy Hale',
          'Tension is who you think you should be. Relaxation is who you are. - Chinese Proverb',
          'Goodness is the only  investment that never fails. - Henry David Thoreau',
          'To hell with circumstances; I create opportunities. - Bruce Lee',
          'Although the world is full of suffering, it is full also of the overcoming of it. - Hellen Keller',
          'The only wa y of discovering the limits of the possible is to venture a little way past them into the impossible. - Arthur C. Clark',
          'When it is obvious that the goals cannot be reached, don’t adjust the goals, adjust the action steps. - Confucius ',
          'Success is ability to go from failure to failure without losing your enthusiasm. - Sir Winston Churchill',
          'The only thing in your control is effort. That’s all, and that’s everything. - Mark Cuban',
          'There is a saying in Tibet an, ‘Tragedy should be utilized as a source of strength.’ No matter what sort of difficulties, how painful experience is, if we lose our hope, that’s our real disaster. - Dalai Lama XIV',
          'You are never too old to set another goal or t o dream a new dream. - C.S. Lewis',
          'We cannot put off living until we are ready. The most salient characteristic of life is its urgency, ‘here and now’ without any possible postponement. Life is fired at us point- blank. - Jose Ortega  y Gasset',
          'The most common way people give up their power is by thinking they don’t have any. - Alice Walker',
          'I think the reward for conformity is that everyone likes you except yourself. - Rita Mae Brown',
          'Nothing can stop the ma n with the right mental attitude from achieving his goal; nothing on Earth can help the man with the wrong mental attitude. - Thomas Jefferson',
          'There is in this world no such force as the force of a man determined to rise. - W.E.B. Du  Bois',
          'Great spirits have always encountered violent oppression from mediocre minds. - Albert Einstein',
          'Success is not to be pursued; it is to be attracted by the person we become. - Jim Rohn',
          'He who conquers others is strong; He  who conquers himself is mighty. - Lao Tse',
          'Nothing great was ever achieved without enthusiasm. - Ralph Waldo Emerson',
          'It takes courage to grow up and turn out to be who you really are. - E.E. Cummings',
          'Imperfection is beauty, madness  is genius and it’s better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe',
          'And when you gaze long into an abyss, the abyss also gazes into you. - Friedrich Nietzsche',
          'Eighty percent of success is showing up. - Wo ody Allen',
          'Luck is what happens when preparation meets opportunity. - Seneca',
          'Don’t wait. The time will never be just right. - Napoleon Hill',
          'Only put off until tomorrow what you are willing to die having left undone. - Pablo  Picasso',
          'Do small things with great love. - Mother Teresa',
          'Sometimes crying or laughing are the only options left, and laughing feels better right now. - Veronica Roth',
          'Do not let what you can’t do interfere with what you can  do. - John Wooden',
          'When you do something noble and beautiful and nobody noticed, do not be sad. For the sun every morning is a beautiful spectacle and yet most of the audience still sleeps. - John Lennon',
          'Always be a first- rate ver sion of yourself, instead of a second- rate version of somebody else. - Judy Garland',
          'Action is the foundational key to all success. - Pablo Picasso',
          'If you cannot do great things, do small things in a great way. - Napoleon Hill',
          'Succes s consists of doing the common things of life uncommonly well. - Unknown',
          'Remember that happiness is a way of travel, not a destination. - Roy L. Goodman',
          'It always seems impossible until it’s done. - Nelson Mandela',
          'To find fulfillm ent…don’t exist with life – embrace it. - Jim Beggs',
          'Being the richest man in the cemetery doesn’t matter to me. Going to bed at night saying we’ve done something wonderful… that’s what matters to me. - Steve Jobs',
          'You were born wi th wings, why prefer to crawl through life?- Rumi',
          'Experience is a brutal teacher, but you learn. My God, do you learn. - C.S.Lewis',
          'Change the way you look at things and the things you look at change. - Wayne W. Dyer',
          'The greate st pleasure in life is doing what people say you can’t do. - Marc Márquez',
          'Setbacks are opportunities for major comebacks. - Travis Wynn',
          'Do what you feel in your heart to be right – for you’ll be criticized anyway. - Eleanor Rooseve lt',
          'The most beautiful thing we can experience is the mysterious. It is the source of all true art and science. - Albert Einstein',
          'The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb',
          'We are  what we repeatedly do. Excellence, therefore, is not an act but a habit. - Aristotle',
          'I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers th at fear. - Nelson Mandela',
          'It’s not the mountains ahead to climb that wear you out; it’s the pebble in your shoe. - Muhammad Ali',
          'A goal property set is halfway reached. - Zig Ziglar',
          'The will to win, the desire to succeed,  the urge to reach your full potential… these are the keys that will unlock the door to personal excellence. - Confucius',
          'Little by little, one travels far. - J.R.R. Tolkien',
          'Nothing is impossible, the word itself says ‘I’m possib le’!- Audrey Hepburn',
          'We are what we repeatedly do. Excellence, therefore, is not an act but a habit. - Aristotle',
          'All life is a chance. So take it! the person who goes furthest is the one who is willing to do and dare. - Dale Car negie',
          'To believe in the things you can see and touch is no belief at all – but to believe in the unseen is a triumph and a blessing. - Abraham Lincoln',
          'Our doubts are traitors, and make us lose the good we oft might win, by fear ing to attempt. - William Shakespeare',
          'Try and fail, but never fail to try. - Jared Leto',
          'If not us, then who? If not now, then when? - John E. Lewis',
          'Each day you must choose, the pain of discipline or the pain of regret. - Er ic Mangini',
          'The way to get started is to quit talking and begin doing. If you can dream it, you can do it. Always remember that this whole thing was started with a dream and a mouse. - Walt Disney',
          'Man’s main task is to give birth  to himself. - Erich Fromm',
          'Long- term consistency trumps short- term intensity. - Bruce Lee',
          'Whether you think you can or think you can’t, you’re right. - Henry Ford',
          'What’s money? A man is a success if he gets up in the morning and  goes to bed at night and in between does what he wants to do. - Bob Dylan',
          'It doesn’t matter where you are coming from. All that matters is where you are going. - Brian Tracy',
          'Keep your face always toward the sunshine, and shadows wil l fall behind you. - Walt Whitman',
          'Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight. - Benjamin Franklin',
          'The two most important days in your life are the day you are born and the day you find o ut why. - Mark Twain',
          'Turn your wounds into wisdom. - Oprah',
          'Inspiration does exist, but it must find you working. - Pablo Picasso',
          'The harder the conflict, the more glorious the triumph. - Thomas Paine',
          'The person who remov es a mountain begins by carrying away small stones. - Japanese Proverb',
          'The only time success comes before work is in the dictionary. - Vince Lombardi',
          'We all have the extraordinary coded within us, waiting to be released. - Jean Ho uston',
          'When a quiet man is moved to passion, it seems the very earth will shake. - Stephanie Barron',
          'Take time to deliberate, but when the time for action has arrived, stop thinking and go in. - Napoleon Bonaparte',
          'Our plans misc arry because they have no aim. When a man does not know what harbor he is making for, no wind is the right wind. - Seneca',
          'Adversity is like a strong wind. It tears away from us all but the things that cannot be torn, so that we see  ourselves as we truly are. - Arthur Golden',
          'If you can’t find something to live for, you best find something to die for. - Tupac',
          'Impatience is the thief of success. - Rebekah L. Pierce',
          'No fear. No distractions. The ability  to let that which does not matter truly slide. - Fight Club',
          'What you get by achieving your goals is not as important as what you become by achieving your goals. - Henry David Thoreau',
          'People often say that motivation doesn’t last . Well, neither does bathing. That’s why we recommend it daily - Zig Ziglar',
          'The question isn’t who is going to let me; it’s who is going to stop me. - Ayn Rand',
          'Life is a journey, not a destination. It is only with the heart th at one can see rightly. What is essential is invisible to the eye. - Antoine de Saint- Exupery',
          'You gotta find a way to survive cause they win when your soul dies. - Tupac',
          'The trouble is you think you have time. - Buddha',
          'Su ccess is not final, failure is not fatal; it is the courage to continue that counts. - Winston Churchill',
          'The thing about motivation is that you don’t really find it finds you. - Ariana Medina',
          'No matter who you are, no matter w hat you did, no matter where you’ve come from, you can always change and become a better version of yourself. - Madonna',
          'Three failures denote uncommon strength. A weakling has not enough grit to fail thrice. - Minna Thomas Antrim',
          'If you want something you never had, you’ve got to do something you’ve never done. - Drina Reed',
          'If you don’t know where you are going any road will get you there- Old Sufi saying',
          'Everything is okay in the end, if it’s not ok, the n it’s not the end. - unknown',
          'People who are crazy enough to think they can change the world, are the ones who do. - Apple, Inc.',
          'A journey of a thousand miles begins with a single step. - Lao Tzu',
          'Successful people are always looking  for opportunities to help others. Unsuccessful people are always asking, ‘What’s in it for me?’ - Brian Tracy',
          'If you hear a voice within you say “you cannot paint," then by all means paint and that voice will be silenced. - Vincent Van G ogh',
          'Do one thing every day that scares you. - Eleanor Roosevelt',
          'Success is the sum of small efforts, repeated day in and day out. - Robert Collier',
          'Keep away from people who try to belittle your ambitions. Small people always do tha t, but the really great make you feel that you, too, can become great. - Mark Twain',
          'Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray',
          'Nothing in the universe can stop you from letting go and starting  over. - Guy Finley',
          'People become really quite remarkable when they start thinking that they can do things. When they believe in themselves they have the first secret of success. - Norman Vincent Peale',
          'Nothing is impossible, the word i tself says ‘I’m possible’!- Audrey Hepburn',
          'You have everything you need to build something far bigger than yourself. - Seth Godin',
          'You are never too old to set another goal or to dream a new dream. - C.S. Lewis',
          'Do not let your fire g o out, spark by irreplaceable spark in the hopeless swamps of the not- quite, the not- yet, and the not- at- all. Do not let the hero in your soul perish in lonely frustration for the life you deserved and have never been able to reach. The  world you desire can be won. It exists.. it is real.. it is possible.. it’s yours. - Ayn Rand',
          'The bigger the mountain, the better the view. - Unknown',
          'A bird sitting on a tree is never afraid of the branch breaking, because her tru st is not on the branch but on it’s own wings. Always believe in yourself."- Unknown',
          'I’d rather have a life of “oh, wells" than a life of “what ifs."- Unknown',
          'Nothing is impossible. The word itself says “I’m Possible."- Unknown',
          'If you do what you always did, you will get what you always got. - Unknown',
          'If winning was easy, losers would do it. - Unknown',
          'You have three choices in life: Give up, give in, or give it all you’ve got. - Unknown',
          'Work until  your idols become rivals. - Unknown',
          'When there is no enemy within, the enemies outside can’t hurt you. - Unknown',
          'There are seven days in the week and someday isn’t one of them. - Unknown',
          'I am not afraid of storms, for I am lea rning how to sail my ship. - Unknown',
          'Don’t stumble over something that’s behind you. - Unknown',
          'Today I will do what others won’t so that tomorrow I can do what others can’t. - Unknown',
          'Always act as if the person you admire is w atching you. - Unknown',
          'No one is taller than the last man standing. - Unknown',
          'I don’t stop when I’m tired. I stop when I’m done. - Unknown',
          'You were born to win, but to be a winner, you must plan to win, prepare to win, and expe ct to win. - Unknown',
          'Suffer the pain of discipline or suffer the pain of regret. - Unknown',
          'All you need is hope and strength: hope that things will eventually get better, and strength to hold on until it does. - Unknown',
          'Where t here is no struggle, there is no strength. - Unknown',
          'When you feel like quitting, think about why you started. - Unknown',
          'Failure is the chance to do better next time. - Unknown',
          'Make sure your worse enemy isn’t between your ears . - Unknown',
          'Every day may not be good. But there is good in every day. - Unknown',
          'Don’t give up what you want most because of what you want now. - Unknown',
          'It’s not about being the best, it’s about being better than you were yest erday. - Unknown',
          'This is your life… and its ending one minute at a time. - Unknown'
          ]
